version: 1
formatters:
  brief:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  precise:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: INFO
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    filename: '../src/llama/log/all_modules.log'
    maxBytes: 1024
    backupCount: 3
    level: DEBUG
    mode: a

loggers:
  src:
    level: DEBUG
    handlers: [file_handler]
    propagate: no

root:
  level: DEBUG
  handlers: [console, file_handler]
  propagate: no
