version: 1
formatters:
  brief:
    format: '%(asctime)s - %(levelname)s - %(message)s'
  precise:
    format: '%(asctime)s - %(levelname)s - %(module)s - %(message)s'

filters:
  allow_foo:
    name: foo_filter
    func: my_module.allow_foo_filter

handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: INFO
    filters: [allow_foo]
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    filename: 'config/log/app_.log'
    maxBytes: 1024
    backupCount: 3

loggers:
  my_module:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console, file]
